### ISSUE TITLE
파이어베이스 env 파일 관련 이슈 및 수정 안내

### ISSUE THREAD

**Issue by senasoon** [likelion-reactproject-lab12/together#15]
@pingandthepong @imironjin @guahyoung @sykang013 @kyungseob7 

안녕하세요! 파이어베이스 관련 이슈 및 프로젝트 내 .env 파일 수정 부탁드립니다.

### 1. 이미지 업로드
데이터 구축을 위해 파이어베이스를 처음 사용했습니다만 아래와 같은 CORS 에러와 함께 업로드가 되지 않는 문제가 발생했습니다. 아래와 같은 에러는 이미지를 업로드할 때 발생했습니다.
```
Access to XMLHttpRequest at '파이어베이스-스토리지-주소' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
```
CORS 문제 해결을 위해 [파이어베이스 문서](https://firebase.google.com/docs/storage/web/download-files?hl=ko)를 참고하여 CORS를 설정했지만 문제가 해결되지 않았습니다.

### 2. 객체 데이터 업로드
이미지 업로드가 아닌 객체 데이터를 생성할 때는 에러는 발생하지 않았지만 데이터가 업로드 되지 않는 문제가 발생했습니다.

### 3. 회원가입 및 문제해결
회원가입 문제가 해결되는지 확인하기 위해 시도해봤으며 API KEY 400 error가 발생했습니다.
![image](https://user-images.githubusercontent.com/102699437/224557918-66615f6b-daa9-427b-998d-2c5e02fe0a0b.png)

.env 파일을 확인했지만 저희 파이어베이스 프로젝트 API KEY가 동일했습니다. .env 파일 문제라고 생각해 .env 파일에 객체로 설정되어 있던 것을 모두 문자열로 수정하여 문제를 해결했습니다.

[Vite env 관련 설정에 관한 문서](https://vitejs-kr.github.io/guide/env-and-mode.html#env-files)를 읽어보시면 아래와 같이 따옴표나 쉼표, 세미콜론 등이 없는 문자열로 정의합니다. 
```
VITE_SOME_KEY=123
DB_PASSWORD=foobar
```

환경변수 파일을 객체로 작성할 수 있는지의 여부는 잘 모르겠지만 일반적으로는 문자열을 사용하기 때문에 저희 프로젝트 .env 파일의 변경이 필요합니다. 디스코드에 공유된 대로 **.env 파일을 변경하고 firebase를 사용**해주시면 되겠습니다!

**Comment by imironjin** [comment]
확인했습니다.

**Comment by guahyoung** [comment]
확인 했습니다.

**Comment by kyungseob7** [comment]
확인했습니다

**Comment by sykang013** [comment]
반영 완료 했습니다. 앞으로 데이터 이슈가 발생하면, 이 내용이 제대로 반영이 되어있나를 가장 먼저 확인하면 좋을 것 같습니다!
