### ISSUE TITLE
깃의 대소문자 구별에 관한 이슈 안내 #21

### ISSUE THREAD

**Issue by sykang013** [likelion-reactproject-lab12/together#22]
@pingandthepong @imironjin @guahyoung @senasoon @sykang013 @kyungseob7 
# 문제점 
- 이슈 넘버 #21 과 관련하여, 깃 자체가 가지고 있는 문제를 개선하기 위한 명령어 입력이 필요합니다.
- 현재 깃은, 의도적으로 파일/폴더명의 대소문자의 구별하지 않고 있습니다만, 폴더 컨벤션을 명확히 하기 위해 대소문자를 구별하도록 설정하려 합니다.
- [참고문서](https://loshy244110.medium.com/git-%EB%8C%80%EC%86%8C%EB%AC%B8%EC%9E%90-%EA%B5%AC%EB%B6%84-%EC%9D%B4%EC%8A%88-b600e93b5b9d)

# 개선방안
- 각자의 터미널에서 아래 명령어를 입력 및 실행 해주신 후, 완료되었다면 완료 코멘트를 달아주세요.
`git config core.ignorecase false`
- 팀 전원이 완료되면, 이 이슈는 닫을 예정입니다.

**Comment by sykang013** [comment]
완료했습니다
![Image](https://user-images.githubusercontent.com/113448786/224596577-e27f41f0-1be7-42dc-9760-53550116f6b3.png)

**Comment by senasoon** [comment]
완료했습니다!

**Comment by guahyoung** [comment]
<img width="629" alt="스크린샷 2023-03-13 오전 11 48 13" src="https://user-images.githubusercontent.com/97956483/224596922-53dbf274-936d-468c-bcaa-63873591da8a.png">
완료했습니다.

**Comment by kyungseob7** [comment]
완료했습니다.

**Comment by sykang013** [comment]
철진님 주현님 완료하시면 댓글 부탁드립니다!  @imironjin @pingandthepong

**Comment by imironjin** [comment]
완료했습니다.
