### ISSUE TITLE
Svg 컴포넌트에 관한 제안

### ISSUE THREAD

**Issue by sykang013** [likelion-reactproject-lab12/together#49]
- @senasoon  세은님께서 만들어주신 Svg 컴포넌트를 사용하여 잘 작동됨을 확인하였습니다.

![Image](https://user-images.githubusercontent.com/113448786/226151410-d7abab37-ed86-44a1-86e0-b56839dd438e.png)

- 다만, 현재 propTypes 가 number로 제한되어있어

![Image](https://user-images.githubusercontent.com/113448786/226151489-2241ff6b-d7e0-4b72-a0de-fa59601f2fd2.png)

- 퍼센테이지 등 문자열이 포함된 단위를 쓰면 아래와 같이 경고가 발생합니다. 

![Image](https://user-images.githubusercontent.com/113448786/226151436-79a21e6d-6d7c-445b-9135-68e4d18893c2.png)

- `number` 를 `oneOfType([number, string])` 로 바꾸는 것은 어떨까요? 그러면 %나 뷰포트 단위를 써도 경고가 뜨지 않습니다. 
```
Svg.propTypes = {
  id: string.isRequired,
  desktopW: oneOfType([number, string]),
  desktopH: oneOfType([number, string]),
  tabletW: oneOfType([number, string]),
  tabletH: oneOfType([number, string]),
  width: oneOfType([number, string]).isRequired,
  height: oneOfType([number, string]).isRequired,
};
```

**Comment by senasoon** [comment]
수정하고 커밋하겠습니다!

**Comment by imironjin** [comment]
@senasoon 
혹시 접근성 관련도 업데이트해서 커밋 가능 할까요?

**Comment by senasoon** [comment]
@imironjin 
aria-label 값을 id값으로 주면 될까요? 예를 들어 id가 cancel-default면 aria-label="cancel-default"가 됩니다. 아니면 Svg 컴포넌트에서 props로 값을 받을까요?

**Comment by imironjin** [comment]
@senasoon 
sprite.svg의 id들이 해당 alt값으로 맞다면 그렇게 써도 괜찮을 것 같습니다.

**Comment by senasoon** [comment]
@imironjin 
수정했습니다 :)

**Comment by sykang013** [comment]
감사합니다! 👍  👍  다음 PR에 반영해서 올려주세요! 이슈는 닫겠습니다.
