### ISSUE TITLE
svg sprite hover시 색상변경 질문

### ISSUE THREAD

**Issue by senasoon** [likelion-reactproject-lab12/together#52]
현재 저희는 svg sprite를 Svg 컴포넌트로 사용하고 있습니다. hover시에 색상을 변경하고 싶은데 일반 svg의 경우 fill을 조정하면 되지만 use를 사용하는 Svg 컴포넌트의 경우 어떻게 설정을 할지 고민입니다. 만약 방법이 없다면 sprite가 아니라 따로 아이콘을 빼서 사용해야할 것 같습니다. 혹시 좋은 방법이 있을까요?

**Comment by sykang013** [comment]
use를 사용하는 경우가 많지않다면, 아이콘을 따로 빼서 사용하는것도 좋을 것 같습니다.
그밖의 '이렇게 할 수도 있지 않을까?' 하는 방법은, sprite.svg 파일안의 "원하는 아이콘"의 id값을 가진 <symbol>에 접근해서, 그 안의 fill 값들을 바꾸는 방법도 가능하지 않을까 싶습니다.

**Comment by senasoon** [comment]
현재 저희 sprite.svg 안에는 이미 fill이나 stroke값이 존재합니다. use를 사용할 때는 svg 요소 내에 이미 fill이나 stroke가 있다면 css로 컨트롤이 어렵다고 합니다. sprite.svg내 이러한 속성들을 제거하고 svg에 다시 색을 지정해주는 작업이 필요해보입니다! 이 작업을 해볼까요?

https://css-tricks.com/change-color-of-svg-on-hover/

**Comment by sykang013** [comment]
새로운 방법을 알아가는 것이니 저는 좋습니다! 그럼 각자 작업을 하는건가요? 아니면 세은님께서 한번 해보신 후 알려주시는 걸까요?

**Comment by senasoon** [comment]
@sykang013 
한번 사용해보고 말씀드리겠습니다!

**Comment by sykang013** [comment]
언제나 선구적 역할을 해주셔서 감사합니다 😭  @senasoon

**Comment by imironjin** [comment]
`sprite.svg`의 `fill`의 값을 `currentColor`로 주고 저희가 컴포넌트 개발을 할 때 해당 SVG에 원하는 `color`값을 지정해주면 될 것 같습니다. 

**참고 사이트**
- [MDN currentColor](https://developer.mozilla.org/ko/docs/Web/CSS/color_value#currentcolor_%ED%82%A4%EC%9B%8C%EB%93%9C)
- https://echobind.com/post/currentcolor-css-property-with-svg

**Comment by senasoon** [comment]
아래 링크도 참고하면 좋을 것 같습니다!
https://github.com/jesstelford/color-svg-sprite#readme
